version: "3.8"

services:
  cheapeate-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: cheapeate-api
    ports:
      - "1337:1337"
    networks:
      - my-custom-network

networks:
  my-custom-network:
    external: true
    ip_address: 172.21.0.2
