version: "3"

services:
  cheapeate-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: cheapeate-api
    ports:
      - "1337:1337"
    ip: "172.21.0.2"
