version: "3.8"

services:
  cheapeate-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: cheapeate-api
    ports:
      - "1337:1337"
    networks:
      - cheapeate_network

networks:
  cheapeate_network:
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
